# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b047e3dd53f49ef38013eef52ea3a9cee6e9a90a813efa6196aef725c21a94b4b328787582ca3ddbf399484bb44a3020b6bfc1b8aca56efde3907aa6b35d0ed

test:
  secret_key_base: f558e58ebbc9af6f8a4b0b7d7c826ece26386bc0c371add45a1edb6ae323c32c0fd6b6bf58330539de84d5c6580de86c4ed346ea1f11082fba1a32655ec6dd85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
